name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  cabal:
    name: "Cabal: GHC ${{ matrix.ghc }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
      - name: Build
        run: cabal new-build --enable-tests --enable-benchmarks
      - name: Test
        run: cabal new-test --enable-tests

  stack:
    name: "Stack: GHC ${{ matrix.ghc }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
          enable-stack: true
          stack-version: latest
      - name: Cache ~/.stack
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
      - name: Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
        env:
          STACK_YAML: stack-${{ matrix.ghc }}.yaml
      - name: Test
        run: stack test --system-ghc
        env:
          STACK_YAML: stack-${{ matrix.ghc }}.yaml
