name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  config:
    name: "Load configuration"
    runs-on: ubuntu-latest
    outputs:
      ghcvers: ${{ steps.set-ghcvers.outputs.ghcvers }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set ghcvers
        id: set-ghcvers
        run: ./test-all.sh github >> $GITHUB_OUTPUT

  cabal:
    name: "Cabal: GHC ${{ matrix.ghc }}"
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ${{fromJSON(needs.config.outputs.ghcvers)}}
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          cabal-version: latest
          ghc-version: ${{ matrix.ghc }}
      - name: Update
        run: cabal v2-update
      - name: Freeze
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-freeze --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-freeze $CONFIG
          fi
      - name: Setup Cache
        run: echo "CURR_MONTH=$(date +%Y%m)" | tee -a "$GITHUB_ENV"
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ env.CURR_MONTH }}-cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ env.CURR_MONTH }}-cabal-${{ matrix.ghc }}-
      - name: Build
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-build --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-build $CONFIG
          fi
      - name: Test
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-test --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-test $CONFIG
          fi
      - name: Haddock
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-haddock --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-haddock $CONFIG
          fi
      - name: Examples
        run: |
          rm -f cabal*.project.freeze
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-build --project-file=cabal-${{ matrix.ghc }}.project $CONFIG ttc-examples -f examples
          else
            cabal v2-build $CONFIG ttc-examples -f examples
          fi

  stack:
    name: "Stack: GHC ${{ matrix.ghc }}"
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ${{fromJSON(needs.config.outputs.ghcvers)}}
    env:
      STACK_YAML: stack-${{ matrix.ghc }}.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          cabal-version: latest
          enable-stack: true
          ghc-version: ${{ matrix.ghc }}
          stack-version: latest
      - name: Setup Cache
        run: echo "CURR_MONTH=$(date +%Y%m)" | tee -a "$GITHUB_ENV"
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ env.CURR_MONTH }}-stack-${{ matrix.ghc }}-${{ hashFiles('ttc.cabal', env.STACK_YAML) }}
          restore-keys: ${{ runner.os }}-${{ env.CURR_MONTH }}-stack-${{ matrix.ghc }}-
      - name: Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
      - name: Test
        run: stack test --system-ghc
      - name: Haddock
        run: stack haddock --system-ghc
      - name: Examples
        run: stack build --system-ghc --flag ttc-examples:examples

  cabal-version:
    name: "Cabal ${{ matrix.cabal }} (GHC ${{ matrix.ghc }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ['2.4.1.0', '3.0.0.0', '3.2.0.0', '3.4.1.0', '3.6.2.0', '3.8.1.0']
        ghc: ['8.2.2']
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          cabal-version: ${{ matrix.cabal }}
          ghc-version: ${{ matrix.ghc }}
      - name: Update
        run: cabal v2-update
      - name: Freeze
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-freeze --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-freeze $CONFIG
          fi
      - name: Setup Cache
        run: echo "CURR_MONTH=$(date +%Y%m)" | tee -a "$GITHUB_ENV"
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ env.CURR_MONTH }}-cabal-version-${{ matrix.cabal }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ env.CURR_MONTH }}-cabal-version-${{ matrix.cabal }}-
      - name: Build
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-build --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-build $CONFIG
          fi
      - name: Test
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-test --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-test $CONFIG
          fi
      - name: Haddock
        run: |
          if [ -f "cabal-${{ matrix.ghc }}.project" ] ; then
            cabal v2-haddock --project-file=cabal-${{ matrix.ghc }}.project $CONFIG
          else
            cabal v2-haddock $CONFIG
          fi
